services:
  - type: web
    name: todo-app
    env: java
    buildCommand: >
      export PATH=/opt/maven/bin:$PATH &&
      export TERM=dumb &&
      export NO_COLOR=1 &&
      mvn clean package -B -DskipTests -Dstyle.color=never --no-transfer-progress
    startCommand: >
      java -jar target/*.jar
      -Dspring.output.ansi.enabled=never
      -Dspring.main.banner-mode=off
    envVars:
      - key: TERM
        value: dumb
      - key: NO_COLOR
        value: "1"
      - key: SPRING_OUTPUT_ANSI_ENABLED
        value: "never"
      - key: SPRING_MAIN_BANNER_MODE
        value: "off"
      - key: PATH
        value: "/opt/maven/bin:/opt/java/bin:${PATH}"
    buildEnv:
      - key: JAVA_VERSION
        value: "17"
      - key: MAVEN_OPTS
        value: "-Dstyle.color=never -Djansi.passthrough=true -Djansi.strip=true"