services:
  - type: web
    name: todo-app
    env: java
    buildCommand: bash .render-buildcommand.sh
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_OUTPUT_ANSI_ENABLED
        value: never
      - key: TERM
        value: dumb