services:
  - type: web
    name: todo-app
    env: java
    buildCommand: TERM=dumb NO_COLOR=1 ./mvnw clean package -DskipTests -B --no-transfer-progress
    startCommand: java -Dspring.output.ansi.enabled=never -jar target/*.jar
    envVars:
      - key: TERM
        value: dumb
      - key: NO_COLOR
        value: "1"
      - key: SPRING_OUTPUT_ANSI_ENABLED
        value: "never"
      - key: SPRING_MAIN_BANNER_MODE
        value: "off"
    buildEnv:
      - key: JAVA_VERSION
        value: "17"
      - key: MAVEN_OPTS
        value: "-Dstyle.color=never --no-transfer-progress"