services:
  - type: web
    name: todo-app
    env: java
    buildCommand: ./mvnw package -B -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_OUTPUT_ANSI_ENABLED
        value: "never"
      - key: TERM
        value: "dumb"
      - key: NO_COLOR
        value: "true"
    buildEnv:
      - key: JAVA_VERSION
        value: "17"
      - key: MAVEN_OPTS
        value: "--no-transfer-progress"