services:
  - type: web
    name: todo-app
    env: java
    buildCommand: TERM=dumb mvn clean package -B -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: ${GOOGLE_CLIENT_ID}
      - key: GOOGLE_CLIENT_SECRET
        value: ${GOOGLE_CLIENT_SECRET}
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: TERM
        value: dumb
    buildEnv:
      - key: JAVA_VERSION
        value: 17.0.7