services:
  - type: web
    name: todo-app
    env: docker
    buildCommand: |
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 17.0.7-tem
      sdk use java 17.0.7-tem
      ./mvnw clean package -DskipTests -B --no-transfer-progress
    startCommand: |
      java -jar target/*.jar \
      -Dspring.output.ansi.enabled=never \
      -Dserver.port=$PORT \
      -Dspring.profiles.active=prod
    envVars:
      - key: TERM
        value: dumb
      - key: NO_COLOR
        value: "1"
      - key: SPRING_OUTPUT_ANSI_ENABLED
        value: "never"
      - key: GOOGLE_CLIENT_ID
        value: 1057612742830-9fj0qlr6lojacitk7n68rsuigj56rpcf.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: MONGODB_URI
        value: mongodb://localhost:27017/firstdb